// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talooner/v1/talooner.proto

// Package talooner.v1 is the Talooner action-payload contract.
//
// Talooner does not define its own gRPC service — OpenTalon fixes that in
// opentalon/proto/plugin.proto, and Talooner declares *actions* the host routes
// to Execute. What lives here are the payload shapes those actions exchange:
// requests are serialized into the ToolCallRequest.args map and the JSON
// `facts` arg; responses come back as JSON in ToolResultResponse
// structured_content (protocol.md). This proto is the typed contract the bot
// consumes as a tagged, generated Go package.
//
// Contract stability is a requirement. A tenant's callers are pinned
// independently and are not told when the cluster upgrades, so this contract
// stays backward-compatible across at least one major version: field numbers
// are append-only, existing fields never change type or meaning, and enum
// values are never renumbered.

package taloonerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvaluateMode selects how evaluate_pr reports its result.
type EvaluateMode int32

const (
	EvaluateMode_EVALUATE_MODE_UNSPECIFIED EvaluateMode = 0 // treated as EXECUTE
	EvaluateMode_EVALUATE_MODE_EXECUTE     EvaluateMode = 1 // return an executable action list
	EvaluateMode_EVALUATE_MODE_PLAN        EvaluateMode = 2 // return a plan only, never executable actions
)

// Enum value maps for EvaluateMode.
var (
	EvaluateMode_name = map[int32]string{
		0: "EVALUATE_MODE_UNSPECIFIED",
		1: "EVALUATE_MODE_EXECUTE",
		2: "EVALUATE_MODE_PLAN",
	}
	EvaluateMode_value = map[string]int32{
		"EVALUATE_MODE_UNSPECIFIED": 0,
		"EVALUATE_MODE_EXECUTE":     1,
		"EVALUATE_MODE_PLAN":        2,
	}
)

func (x EvaluateMode) Enum() *EvaluateMode {
	p := new(EvaluateMode)
	*p = x
	return p
}

func (x EvaluateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvaluateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_talooner_v1_talooner_proto_enumTypes[0].Descriptor()
}

func (EvaluateMode) Type() protoreflect.EnumType {
	return &file_talooner_v1_talooner_proto_enumTypes[0]
}

func (x EvaluateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvaluateMode.Descriptor instead.
func (EvaluateMode) EnumDescriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{0}
}

// Verb is the abstract action vocabulary (engine.md, "Abstract action
// vocabulary"). The plugin returns verbs as data; the bot translates them to
// GitHub. The set is closed — validate_ruleset rejects any verb outside it.
//
// Retraction. Each evaluate_pr returns the COMPLETE current action set (full
// re-derivation, never a delta), so an action that fired before and is absent
// now has been retracted: its rule no longer matches the facts. The bot diffs
// the new set against what it previously executed and undoes the difference.
// The per-verb comments below say what that undo means; the plugin owns the
// full-state guarantee, the bot owns the GitHub effect.
type Verb int32

const (
	Verb_VERB_UNSPECIFIED Verb = 0
	// approve target "pr". Fires only when no strict rule defeated it.
	// Retraction: the prior approval is withdrawn — the bot dismisses its review.
	Verb_VERB_APPROVE Verb = 1
	// block target "pr.merge".
	// Retraction: the block is lifted — Talooner no longer blocks the merge.
	Verb_VERB_BLOCK Verb = 2
	// comment target + text; {attr.x} interpolation already resolved.
	// Retraction: the bot keys its comment so re-posting is idempotent and an
	// absent comment can be resolved/hidden.
	Verb_VERB_COMMENT Verb = 3
	// assign target + assignee (an attr like "user.owner" arrives resolved to a
	// value, not the literal string).
	// Retraction: the assignment the bot made is removed.
	Verb_VERB_ASSIGN Verb = 4
	// require "review.<target>".
	// Retraction: the review requirement the bot added is dropped.
	Verb_VERB_REQUIRE Verb = 5
	// notify target + text; the bot dispatches through an OpenTalon channel.
	// Deferred bot-side to v1.5 (needs a configured channel), but the plugin
	// returns it and validate_ruleset accepts it. One-shot: a sent notification
	// cannot be unsent, so there is nothing to retract.
	Verb_VERB_NOTIFY Verb = 6
	// emit name; asserts event.<name>=true in the scope, no external effect.
	// Retraction: the event fact is re-derived each run like any bot fact, so
	// there is nothing external to undo.
	Verb_VERB_EMIT Verb = 7
)

// Enum value maps for Verb.
var (
	Verb_name = map[int32]string{
		0: "VERB_UNSPECIFIED",
		1: "VERB_APPROVE",
		2: "VERB_BLOCK",
		3: "VERB_COMMENT",
		4: "VERB_ASSIGN",
		5: "VERB_REQUIRE",
		6: "VERB_NOTIFY",
		7: "VERB_EMIT",
	}
	Verb_value = map[string]int32{
		"VERB_UNSPECIFIED": 0,
		"VERB_APPROVE":     1,
		"VERB_BLOCK":       2,
		"VERB_COMMENT":     3,
		"VERB_ASSIGN":      4,
		"VERB_REQUIRE":     5,
		"VERB_NOTIFY":      6,
		"VERB_EMIT":        7,
	}
)

func (x Verb) Enum() *Verb {
	p := new(Verb)
	*p = x
	return p
}

func (x Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_talooner_v1_talooner_proto_enumTypes[1].Descriptor()
}

func (Verb) Type() protoreflect.EnumType {
	return &file_talooner_v1_talooner_proto_enumTypes[1]
}

func (x Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verb.Descriptor instead.
func (Verb) EnumDescriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{1}
}

// Severity classifies a diagnostic or warning.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_ERROR       Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_INFO        Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_ERROR",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_INFO",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_ERROR":       1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_INFO":        3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_talooner_v1_talooner_proto_enumTypes[2].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_talooner_v1_talooner_proto_enumTypes[2]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{2}
}

// Action is one abstract action the engine decided should fire, with its
// arguments already resolved against the matched facts. Which scalar fields are
// set depends on the verb (see Verb).
//
// Interpolation is resolved before the action leaves the plugin: a text like
// "…{attr.user.owner}…" arrives filled in. One wrinkle: {item.<field>} resolves
// only for {item.name}; {item.id} renders literally, so templates use {id} or
// {attr.x}.
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verb          Verb                   `protobuf:"varint,1,opt,name=verb,proto3,enum=talooner.v1.Verb" json:"verb,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`     // approve/block/comment/assign/require target
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`         // comment / notify text, interpolation resolved
	Assignee      string                 `protobuf:"bytes,4,opt,name=assignee,proto3" json:"assignee,omitempty"` // assign: resolved user or team
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`         // emit: event name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetVerb() Verb {
	if x != nil {
		return x.Verb
	}
	return Verb_VERB_UNSPECIFIED
}

func (x *Action) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Action) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Action) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Warning is a non-fatal condition surfaced alongside a decision (e.g. an
// unresolved approve/block tie that fired both).
type Warning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{1}
}

func (x *Warning) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Warning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RuleFiring records one rule's contribution to a decision, for the audit
// trail. Extended as explain_pr (P-C5) and decision persistence (P-B9) land.
type RuleFiring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Priority      string                 `protobuf:"bytes,2,opt,name=priority,proto3" json:"priority,omitempty"` // CRITICAL | HIGH | MEDIUM | LOW
	Strict        bool                   `protobuf:"varint,3,opt,name=strict,proto3" json:"strict,omitempty"`
	Overrides     []string               `protobuf:"bytes,4,rep,name=overrides,proto3" json:"overrides,omitempty"` // rules this one defeated
	Defeated      bool                   `protobuf:"varint,5,opt,name=defeated,proto3" json:"defeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleFiring) Reset() {
	*x = RuleFiring{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleFiring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleFiring) ProtoMessage() {}

func (x *RuleFiring) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleFiring.ProtoReflect.Descriptor instead.
func (*RuleFiring) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{2}
}

func (x *RuleFiring) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *RuleFiring) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *RuleFiring) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *RuleFiring) GetOverrides() []string {
	if x != nil {
		return x.Overrides
	}
	return nil
}

func (x *RuleFiring) GetDefeated() bool {
	if x != nil {
		return x.Defeated
	}
	return false
}

// Explain is the human- and machine-readable account of why a decision came
// out the way it did.
type Explain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Firings       []*RuleFiring          `protobuf:"bytes,2,rep,name=firings,proto3" json:"firings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Explain) Reset() {
	*x = Explain{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Explain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Explain) ProtoMessage() {}

func (x *Explain) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Explain.ProtoReflect.Descriptor instead.
func (*Explain) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{3}
}

func (x *Explain) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Explain) GetFirings() []*RuleFiring {
	if x != nil {
		return x.Firings
	}
	return nil
}

// Diagnostic is one finding from validate_ruleset — a parse/compile error or a
// verb-vocabulary violation.
type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      Severity               `protobuf:"varint,1,opt,name=severity,proto3,enum=talooner.v1.Severity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	Rule          string                 `protobuf:"bytes,5,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{4}
}

func (x *Diagnostic) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Diagnostic) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Diagnostic) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

// EvaluatePrRequest is the evaluate_pr payload. facts_json carries the extracted
// PR facts as JSON (the `facts` arg on the wire); the rest map to string args.
type EvaluatePrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Pr            int32                  `protobuf:"varint,2,opt,name=pr,proto3" json:"pr,omitempty"`
	HeadSha       string                 `protobuf:"bytes,3,opt,name=head_sha,json=headSha,proto3" json:"head_sha,omitempty"`
	FactsJson     string                 `protobuf:"bytes,4,opt,name=facts_json,json=factsJson,proto3" json:"facts_json,omitempty"`
	Ruleset       string                 `protobuf:"bytes,5,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	Mode          EvaluateMode           `protobuf:"varint,6,opt,name=mode,proto3,enum=talooner.v1.EvaluateMode" json:"mode,omitempty"`
	Force         bool                   `protobuf:"varint,7,opt,name=force,proto3" json:"force,omitempty"` // bypass the llm_review fact cache for this evaluation only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePrRequest) Reset() {
	*x = EvaluatePrRequest{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePrRequest) ProtoMessage() {}

func (x *EvaluatePrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePrRequest.ProtoReflect.Descriptor instead.
func (*EvaluatePrRequest) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluatePrRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *EvaluatePrRequest) GetPr() int32 {
	if x != nil {
		return x.Pr
	}
	return 0
}

func (x *EvaluatePrRequest) GetHeadSha() string {
	if x != nil {
		return x.HeadSha
	}
	return ""
}

func (x *EvaluatePrRequest) GetFactsJson() string {
	if x != nil {
		return x.FactsJson
	}
	return ""
}

func (x *EvaluatePrRequest) GetRuleset() string {
	if x != nil {
		return x.Ruleset
	}
	return ""
}

func (x *EvaluatePrRequest) GetMode() EvaluateMode {
	if x != nil {
		return x.Mode
	}
	return EvaluateMode_EVALUATE_MODE_UNSPECIFIED
}

func (x *EvaluatePrRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// EvaluatePrResponse is the decision. In execute mode `actions` is populated and
// `plan` is empty; in plan mode `plan` is populated and `actions` is empty —
// they are distinct fields so a plan can never be mistaken for something to run.
type EvaluatePrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Plan          []*Action              `protobuf:"bytes,2,rep,name=plan,proto3" json:"plan,omitempty"`
	Explain       *Explain               `protobuf:"bytes,3,opt,name=explain,proto3" json:"explain,omitempty"`
	Warnings      []*Warning             `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePrResponse) Reset() {
	*x = EvaluatePrResponse{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePrResponse) ProtoMessage() {}

func (x *EvaluatePrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePrResponse.ProtoReflect.Descriptor instead.
func (*EvaluatePrResponse) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluatePrResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *EvaluatePrResponse) GetPlan() []*Action {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *EvaluatePrResponse) GetExplain() *Explain {
	if x != nil {
		return x.Explain
	}
	return nil
}

func (x *EvaluatePrResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// ValidateRulesetRequest / ValidateRulesetResponse back validate_ruleset.
type ValidateRulesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ruleset       string                 `protobuf:"bytes,1,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRulesetRequest) Reset() {
	*x = ValidateRulesetRequest{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRulesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRulesetRequest) ProtoMessage() {}

func (x *ValidateRulesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRulesetRequest.ProtoReflect.Descriptor instead.
func (*ValidateRulesetRequest) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateRulesetRequest) GetRuleset() string {
	if x != nil {
		return x.Ruleset
	}
	return ""
}

type ValidateRulesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRulesetResponse) Reset() {
	*x = ValidateRulesetResponse{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRulesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRulesetResponse) ProtoMessage() {}

func (x *ValidateRulesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRulesetResponse.ProtoReflect.Descriptor instead.
func (*ValidateRulesetResponse) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateRulesetResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateRulesetResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// WhoamiResponse is the capability handshake. protocol_version lets a caller
// fail fast on version skew; models/features let it know whether llm_review is
// available before loading a ruleset that depends on it.
type WhoamiResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tenant          string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Models          []string               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	Features        []string               `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	Quota           *Quota                 `protobuf:"bytes,5,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WhoamiResponse) Reset() {
	*x = WhoamiResponse{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResponse) ProtoMessage() {}

func (x *WhoamiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResponse.ProtoReflect.Descriptor instead.
func (*WhoamiResponse) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{9}
}

func (x *WhoamiResponse) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *WhoamiResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *WhoamiResponse) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *WhoamiResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *WhoamiResponse) GetQuota() *Quota {
	if x != nil {
		return x.Quota
	}
	return nil
}

// Quota reports the tenant's LLM budget usage for the current window.
type Quota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LlmCallsUsed  int64                  `protobuf:"varint,1,opt,name=llm_calls_used,json=llmCallsUsed,proto3" json:"llm_calls_used,omitempty"`
	LlmCallsLimit int64                  `protobuf:"varint,2,opt,name=llm_calls_limit,json=llmCallsLimit,proto3" json:"llm_calls_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quota) Reset() {
	*x = Quota{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{10}
}

func (x *Quota) GetLlmCallsUsed() int64 {
	if x != nil {
		return x.LlmCallsUsed
	}
	return 0
}

func (x *Quota) GetLlmCallsLimit() int64 {
	if x != nil {
		return x.LlmCallsLimit
	}
	return 0
}

// IsSubscribedResponse answers is_subscribed. subscribed is false for a PR that
// was never seen — not an error. since is the unix time (seconds) the current
// state was established, 0 when never set.
type IsSubscribedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribed    bool                   `protobuf:"varint,1,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	Since         int64                  `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSubscribedResponse) Reset() {
	*x = IsSubscribedResponse{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSubscribedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSubscribedResponse) ProtoMessage() {}

func (x *IsSubscribedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSubscribedResponse.ProtoReflect.Descriptor instead.
func (*IsSubscribedResponse) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{11}
}

func (x *IsSubscribedResponse) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

func (x *IsSubscribedResponse) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// SetSubscriptionResponse answers set_subscription with the resulting state.
type SetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribed    bool                   `protobuf:"varint,1,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSubscriptionResponse) Reset() {
	*x = SetSubscriptionResponse{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSubscriptionResponse) ProtoMessage() {}

func (x *SetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{12}
}

func (x *SetSubscriptionResponse) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

// AssertFactsResponse answers assert_facts. Store-only in v1 (decision 20): it
// reports which attributes were accepted and stored and which were rejected,
// and carries NO action list — the caller is a workflow run that exited long
// before this, and the plugin holds no GitHub credential, so a woken rule has
// nobody to act on. Accepted facts enter a verdict at the next evaluate_pr.
type AssertFactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      []string               `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      []*RejectedFact        `protobuf:"bytes,2,rep,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertFactsResponse) Reset() {
	*x = AssertFactsResponse{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertFactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertFactsResponse) ProtoMessage() {}

func (x *AssertFactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertFactsResponse.ProtoReflect.Descriptor instead.
func (*AssertFactsResponse) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{13}
}

func (x *AssertFactsResponse) GetAccepted() []string {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *AssertFactsResponse) GetRejected() []*RejectedFact {
	if x != nil {
		return x.Rejected
	}
	return nil
}

// RejectedFact is one attribute assert_facts refused, with why.
type RejectedFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     string                 `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedFact) Reset() {
	*x = RejectedFact{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedFact) ProtoMessage() {}

func (x *RejectedFact) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedFact.ProtoReflect.Descriptor instead.
func (*RejectedFact) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{14}
}

func (x *RejectedFact) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *RejectedFact) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ExplainPrResponse answers explain_pr: the persisted explanation for a PR's
// decision at a given head sha. Because the decision and its explanation outlive
// the facts (facts.md), this renders even after retention has swept the facts.
type ExplainPrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Explain       *Explain               `protobuf:"bytes,1,opt,name=explain,proto3" json:"explain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainPrResponse) Reset() {
	*x = ExplainPrResponse{}
	mi := &file_talooner_v1_talooner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainPrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainPrResponse) ProtoMessage() {}

func (x *ExplainPrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talooner_v1_talooner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainPrResponse.ProtoReflect.Descriptor instead.
func (*ExplainPrResponse) Descriptor() ([]byte, []int) {
	return file_talooner_v1_talooner_proto_rawDescGZIP(), []int{15}
}

func (x *ExplainPrResponse) GetExplain() *Explain {
	if x != nil {
		return x.Explain
	}
	return nil
}

var File_talooner_v1_talooner_proto protoreflect.FileDescriptor

const file_talooner_v1_talooner_proto_rawDesc = "" +
	"\n" +
	"\x1atalooner/v1/talooner.proto\x12\vtalooner.v1\"\x8b\x01\n" +
	"\x06Action\x12%\n" +
	"\x04verb\x18\x01 \x01(\x0e2\x11.talooner.v1.VerbR\x04verb\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1a\n" +
	"\bassignee\x18\x04 \x01(\tR\bassignee\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"7\n" +
	"\aWarning\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8e\x01\n" +
	"\n" +
	"RuleFiring\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\tR\bpriority\x12\x16\n" +
	"\x06strict\x18\x03 \x01(\bR\x06strict\x12\x1c\n" +
	"\toverrides\x18\x04 \x03(\tR\toverrides\x12\x1a\n" +
	"\bdefeated\x18\x05 \x01(\bR\bdefeated\"V\n" +
	"\aExplain\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x121\n" +
	"\afirings\x18\x02 \x03(\v2\x17.talooner.v1.RuleFiringR\afirings\"\x99\x01\n" +
	"\n" +
	"Diagnostic\x121\n" +
	"\bseverity\x18\x01 \x01(\x0e2\x15.talooner.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\x12\x12\n" +
	"\x04rule\x18\x05 \x01(\tR\x04rule\"\xd0\x01\n" +
	"\x11EvaluatePrRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x0e\n" +
	"\x02pr\x18\x02 \x01(\x05R\x02pr\x12\x19\n" +
	"\bhead_sha\x18\x03 \x01(\tR\aheadSha\x12\x1d\n" +
	"\n" +
	"facts_json\x18\x04 \x01(\tR\tfactsJson\x12\x18\n" +
	"\aruleset\x18\x05 \x01(\tR\aruleset\x12-\n" +
	"\x04mode\x18\x06 \x01(\x0e2\x19.talooner.v1.EvaluateModeR\x04mode\x12\x14\n" +
	"\x05force\x18\a \x01(\bR\x05force\"\xce\x01\n" +
	"\x12EvaluatePrResponse\x12-\n" +
	"\aactions\x18\x01 \x03(\v2\x13.talooner.v1.ActionR\aactions\x12'\n" +
	"\x04plan\x18\x02 \x03(\v2\x13.talooner.v1.ActionR\x04plan\x12.\n" +
	"\aexplain\x18\x03 \x01(\v2\x14.talooner.v1.ExplainR\aexplain\x120\n" +
	"\bwarnings\x18\x04 \x03(\v2\x14.talooner.v1.WarningR\bwarnings\"2\n" +
	"\x16ValidateRulesetRequest\x12\x18\n" +
	"\aruleset\x18\x01 \x01(\tR\aruleset\"j\n" +
	"\x17ValidateRulesetResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x129\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x17.talooner.v1.DiagnosticR\vdiagnostics\"\xb1\x01\n" +
	"\x0eWhoamiResponse\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12\x16\n" +
	"\x06models\x18\x03 \x03(\tR\x06models\x12\x1a\n" +
	"\bfeatures\x18\x04 \x03(\tR\bfeatures\x12(\n" +
	"\x05quota\x18\x05 \x01(\v2\x12.talooner.v1.QuotaR\x05quota\"U\n" +
	"\x05Quota\x12$\n" +
	"\x0ellm_calls_used\x18\x01 \x01(\x03R\fllmCallsUsed\x12&\n" +
	"\x0fllm_calls_limit\x18\x02 \x01(\x03R\rllmCallsLimit\"L\n" +
	"\x14IsSubscribedResponse\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x01 \x01(\bR\n" +
	"subscribed\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x03R\x05since\"9\n" +
	"\x17SetSubscriptionResponse\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x01 \x01(\bR\n" +
	"subscribed\"h\n" +
	"\x13AssertFactsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x03(\tR\baccepted\x125\n" +
	"\brejected\x18\x02 \x03(\v2\x19.talooner.v1.RejectedFactR\brejected\"D\n" +
	"\fRejectedFact\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\tR\tattribute\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"C\n" +
	"\x11ExplainPrResponse\x12.\n" +
	"\aexplain\x18\x01 \x01(\v2\x14.talooner.v1.ExplainR\aexplain*`\n" +
	"\fEvaluateMode\x12\x1d\n" +
	"\x19EVALUATE_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVALUATE_MODE_EXECUTE\x10\x01\x12\x16\n" +
	"\x12EVALUATE_MODE_PLAN\x10\x02*\x93\x01\n" +
	"\x04Verb\x12\x14\n" +
	"\x10VERB_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fVERB_APPROVE\x10\x01\x12\x0e\n" +
	"\n" +
	"VERB_BLOCK\x10\x02\x12\x10\n" +
	"\fVERB_COMMENT\x10\x03\x12\x0f\n" +
	"\vVERB_ASSIGN\x10\x04\x12\x10\n" +
	"\fVERB_REQUIRE\x10\x05\x12\x0f\n" +
	"\vVERB_NOTIFY\x10\x06\x12\r\n" +
	"\tVERB_EMIT\x10\a*a\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x03BBZ@github.com/opentalon/talooner-plugin/proto/taloonerpb;taloonerpbb\x06proto3"

var (
	file_talooner_v1_talooner_proto_rawDescOnce sync.Once
	file_talooner_v1_talooner_proto_rawDescData []byte
)

func file_talooner_v1_talooner_proto_rawDescGZIP() []byte {
	file_talooner_v1_talooner_proto_rawDescOnce.Do(func() {
		file_talooner_v1_talooner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talooner_v1_talooner_proto_rawDesc), len(file_talooner_v1_talooner_proto_rawDesc)))
	})
	return file_talooner_v1_talooner_proto_rawDescData
}

var file_talooner_v1_talooner_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_talooner_v1_talooner_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_talooner_v1_talooner_proto_goTypes = []any{
	(EvaluateMode)(0),               // 0: talooner.v1.EvaluateMode
	(Verb)(0),                       // 1: talooner.v1.Verb
	(Severity)(0),                   // 2: talooner.v1.Severity
	(*Action)(nil),                  // 3: talooner.v1.Action
	(*Warning)(nil),                 // 4: talooner.v1.Warning
	(*RuleFiring)(nil),              // 5: talooner.v1.RuleFiring
	(*Explain)(nil),                 // 6: talooner.v1.Explain
	(*Diagnostic)(nil),              // 7: talooner.v1.Diagnostic
	(*EvaluatePrRequest)(nil),       // 8: talooner.v1.EvaluatePrRequest
	(*EvaluatePrResponse)(nil),      // 9: talooner.v1.EvaluatePrResponse
	(*ValidateRulesetRequest)(nil),  // 10: talooner.v1.ValidateRulesetRequest
	(*ValidateRulesetResponse)(nil), // 11: talooner.v1.ValidateRulesetResponse
	(*WhoamiResponse)(nil),          // 12: talooner.v1.WhoamiResponse
	(*Quota)(nil),                   // 13: talooner.v1.Quota
	(*IsSubscribedResponse)(nil),    // 14: talooner.v1.IsSubscribedResponse
	(*SetSubscriptionResponse)(nil), // 15: talooner.v1.SetSubscriptionResponse
	(*AssertFactsResponse)(nil),     // 16: talooner.v1.AssertFactsResponse
	(*RejectedFact)(nil),            // 17: talooner.v1.RejectedFact
	(*ExplainPrResponse)(nil),       // 18: talooner.v1.ExplainPrResponse
}
var file_talooner_v1_talooner_proto_depIdxs = []int32{
	1,  // 0: talooner.v1.Action.verb:type_name -> talooner.v1.Verb
	5,  // 1: talooner.v1.Explain.firings:type_name -> talooner.v1.RuleFiring
	2,  // 2: talooner.v1.Diagnostic.severity:type_name -> talooner.v1.Severity
	0,  // 3: talooner.v1.EvaluatePrRequest.mode:type_name -> talooner.v1.EvaluateMode
	3,  // 4: talooner.v1.EvaluatePrResponse.actions:type_name -> talooner.v1.Action
	3,  // 5: talooner.v1.EvaluatePrResponse.plan:type_name -> talooner.v1.Action
	6,  // 6: talooner.v1.EvaluatePrResponse.explain:type_name -> talooner.v1.Explain
	4,  // 7: talooner.v1.EvaluatePrResponse.warnings:type_name -> talooner.v1.Warning
	7,  // 8: talooner.v1.ValidateRulesetResponse.diagnostics:type_name -> talooner.v1.Diagnostic
	13, // 9: talooner.v1.WhoamiResponse.quota:type_name -> talooner.v1.Quota
	17, // 10: talooner.v1.AssertFactsResponse.rejected:type_name -> talooner.v1.RejectedFact
	6,  // 11: talooner.v1.ExplainPrResponse.explain:type_name -> talooner.v1.Explain
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_talooner_v1_talooner_proto_init() }
func file_talooner_v1_talooner_proto_init() {
	if File_talooner_v1_talooner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talooner_v1_talooner_proto_rawDesc), len(file_talooner_v1_talooner_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_talooner_v1_talooner_proto_goTypes,
		DependencyIndexes: file_talooner_v1_talooner_proto_depIdxs,
		EnumInfos:         file_talooner_v1_talooner_proto_enumTypes,
		MessageInfos:      file_talooner_v1_talooner_proto_msgTypes,
	}.Build()
	File_talooner_v1_talooner_proto = out.File
	file_talooner_v1_talooner_proto_goTypes = nil
	file_talooner_v1_talooner_proto_depIdxs = nil
}
